FROM centos:latest
MAINTAINER Jose Arenas
ENV build_date 2016-02-10

COPY install/install-depot_tools.sh /install-depot_tools.sh
COPY install/install-libsrtp.sh /install-libsrtp.sh
COPY install/install-Opus.sh /install-Opus.sh
COPY install/install-Speex.sh /install-Speex.sh
COPY install/install-libvpx.sh /install-libvpx.sh
COPY install/install-mp4v2.sh /install-mp4v2.sh
COPY install/install-xmlrpc.sh /install-xmlrpc.sh
#COPY ffmpeg /usr/local/src/ffmpeg 
COPY install/install-FFMPEG.sh /install-FFMPEG.sh
COPY install/install-X264.sh /install-X264.sh
COPY install/install-yasm.sh /install-yasm.sh
COPY install/install-rpm.sh /install-rpm.sh

RUN chmod +x /install-*.sh
RUN /bin/bash -c "sh -x /install-rpm.sh"
RUN /bin/bash -c "sh -x /install-yasm.sh"
RUN /bin/bash -c "sh -x /install-X264.sh"
RUN /bin/bash -c "sh -x /install-FFMPEG.sh"
RUN /bin/bash -c "sh -x /install-xmlrpc.sh"
RUN /bin/bash -c "sh -x /install-mp4v2.sh"
RUN /bin/bash -c "sh -x /install-libvpx.sh"
RUN /bin/bash -c "sh -x /install-Speex.sh"
RUN /bin/bash -c "sh -x /install-Opus.sh"
RUN /bin/bash -c "sh -x /install-libsrtp.sh"
RUN /bin/bash -c "sh -x /install-depot_tools.sh"

COPY config.mk /usr/local/src/medooze/mcu/config.mk

COPY ld.so.conf /etc/ld.so.conf
RUN ldconfig

WORKDIR /usr/local/src/medooze/mcu
COPY mcu /usr/local/src/medooze/mcu/

COPY mediamixer /mediamixer
RUN chmod 777 /mediamixer
RUN chmod +x /usr/local/src/medooze/mcu/bin/release/mcu

WORKDIR /
ENTRYPOINT ["/mediamixer"]

CMD ["start"]
